version: 2

sources:
  - name: staging
    database: de-zoomcamp2025-448100
    schema: trips_data_all
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata
  